config/routes.rb
Rails.application.routes.draw do

  resources 'cats'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = %w(red blue yellow green purple )

  validates :birth_date, :name, :description, presence: true
  validates :color, inclusion: { in: COLORS,
    message: "%{value} is not a valid color" }, presence: true
  validates :sex, inclusion: { in: %w{M F}, message: "Please choose 'M' or 'F'"}

  has_many :rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def age
    Time.now.year - birth_date.year
  end

  def colors
    @colors = COLORS
  end

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :status, inclusion: { in: ['PENDING', 'APPROVED'], message: "Invalid status" }
  validates :cat_id, :start_date, :end_date, :status, presence: true

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  def overlapping_requests
    # overlap_start = CatRentalRequest.where.not(["end_date <= ?", self.start_date]).to_a
    # overlap_end = CatRentalRequest.where.not(["start_date >= ?", self.end_date]).to_a
    #
    # (overlap_start + overlap_end).uniq

    one = CatRentalRequest.where(["? > start_date and ? < start_date"])
  end

  def okay_req

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all

    if @cats
      render :index
    else
      render text: "cats does not exist"
    end
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def edit
    @cat = Cat.find(params[:id])
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update_attributes(cat_params)
      render cat_url(@cat)
    else
      render edit_cat_url
    end

  end


  def create

    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end


  private
  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_controller_helper.rb
module CatsControllerHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<% action_url = (action == :new) ? new_cat_url : edit_cat_url(cat) %>

<form action="index.html" method="post">

<% if action_url != new_cat_url  %>
  <input type="hidden" name="_method" value="patch">
<% end %>


  <label for="name">Name: </label>
  <input type="text" name="name" value= "<%= cat.name %>">

  <br>

  <label for="radio button">Sex: </label>
  M<input type="radio" name="radio button" value="M" <%= cat.sex == 'M' ? 'checked' : ''%> >
  F<input type="radio" name="radio button" value="F" <%= cat.sex == 'F' ? 'checked' : ''%> >

  <br>

  <select name="colors">
    <option disabled <%= cat.color.nil? ? 'selected' : '' %> >--Select Color--</option>
    <option value="Red" <%= cat.color == "red" ? 'selected' : '' %> >Red</option>
    <option value="Blue" <%= cat.color == "blue" ? 'selected' : '' %> >Blue</option>
    <option value="Yellow" <%= cat.color == "yellow" ? 'selected' : '' %> >Yellow</option>
    <option value="Green" <%= cat.color == "green" ? 'selected' : '' %> >Green</option>
    <option value="Purple" <%= cat.color == "purple" ? 'selected' : '' %> >Purple</option>
  </select>

  <br>

  <input type="date" name="Birthday" value=<%= cat.birth_date %>>

  <br>

  <label>Description<br><textarea name="name" rows="8" cols="80"><%= cat.description%></textarea></label>


</form>

app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, action: :edit %>

app/views/cats/index.html.erb
<h1>Cats</h1>

<% @cats.each do |cat| %>
  <li><%= link_to cat.name, cat_url(cat) %></li>
<% end %>

app/views/cats/new.html.erb
<%= render 'form', cat: @cat, action: :new %>

app/views/cats/show.html.erb
<head>
<style>
table, th, td {
    border: 1px solid black;
}
</style>
</head>

<h1><%= @cat.name %></h1>

<table>
  <tr>
    <th>Birth Date</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <!-- <%#= stylesheet_link_tag    'application', media: 'all' %>
  <%#= javascript_include_tag 'application' %> -->
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>